version: '3.7'

services:
    web:
        image: nginx:1.12
        ports:
            - "8080:80"
        volumes:
            - .:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        image: php:7.1-fpm
        volumes:
            - .:/code